export const NEXT_PUBLIC_EXTREME_IP_LOOKUP_API_KEY =
  process.env.NEXT_PUBLIC_EXTREME_IP_LOOKUP_API_KEY;

export const GOOGLE_SEARCH_API_KEY = process.env.GOOGLE_SEARCH_API_KEY;
export const GOOGLE_SEARCH_CONTEXT_KEY = process.env.GOOGLE_SEARCH_CONTEXT_KEY;
